# User config
author: "i do like X"
tagline: "i do like X - a personal blog"
description: "A blog of all things i do like(?)"
keywords: "Blog"
like_keywords:
  - "Tech"
  - "Reading"
# email: "dtghose@gmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
